# Generated by Django 2.1.5 on 2019-07-02 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAlgTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_length', models.IntegerField(choices=[('10', '10'), ('100', '100'), ('1000', '1000'), ('10000', '10000')])),
                ('unique_keys', models.BooleanField(default=True)),
                ('test_date', models.DateTimeField(auto_now=True)),
                ('bubble', models.FloatField(default=0)),
                ('select', models.FloatField(default=0)),
                ('merge', models.FloatField(default=0)),
                ('heap', models.FloatField(default=0)),
                ('quick', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SingleAlgTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('bubble', 'bubble sort'), ('select', 'select sort'), ('merge', 'merge sort'), ('heap', 'heap sort'), ('quick', 'quick sort')], max_length=20)),
                ('unique_keys', models.BooleanField(default=True)),
                ('test_date', models.DateTimeField(auto_now=True)),
                ('time_10', models.FloatField(default=0)),
                ('time_100', models.FloatField(default=0)),
                ('time_1000', models.FloatField(default=0)),
                ('time_10000', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
